trigger:
  batch: true
  branches:
    include:
      - main
      - feature/**
      - hotfix/**

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  project: "**/Blogsphere.User.Api.csproj"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  dotnetVersion: "8.x"
  githubConnection: "github.com_sharthak1095"
  repositoryName: "Scaler-io/Blogsphere.User.Api"

stages:
  - stage: Build
    displayName: "Build User Api"
    jobs:
      - job: build
        displayName: "Build job"
        steps:
          - template: ./build/build.yml
            parameters:
              project: $(project)
              buildConfiguration: $(buildConfiguration)
              buildPlatform: $(buildPlatform)
              dotnetVersion: $(dotnetVersion)

  - stage: GithubRelease
    displayName: "Github release job"
    # condition: and(succeeded(), notIn(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: GithubRelease
        displayName: "Github release"
        environment: blogsphere-user-api-github-release-env
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./deploy/github-release.yml
                  parameters:
                    githubConnection: $(githubConnection)
                    repositoryName: $(repositoryName)
