services:
  blogsphere.user.api:
    image: ${DOCKER_REGISTRY-}blogsphereuserapi
    build:
      context: .
      dockerfile: Blogsphere.User.Api/Dockerfile

networks:
  blogsphere_dev_net:
    external: true
